[pygame]
resolution = [1000, 800]

[FPS]
calc_target_FPS = 300
visual_target_FPS = 100

[simulation]
sim_speed_mult = 1

[simulation.arena]
arena_dimensions = [100,100]
arena_surface_dims = [700,700]
arena_surface_location = [50,50]
arena_sprite_path = '/assets/reef_650x650_darker.png'

[simulation.fishes]
N_fishes = 100
N_species = 6
min_fish_vel = 1.5
max_fish_vel = 15
turn_speed = 3.14
repelling_distance = 1.5
aligning_distance = 3.3

[simulation.fishes.gfx]
N_fish_sprites = 3
min_fish_visual_size_coeff = 0.8 
max_fish_visual_size_coeff = 1.3
fish_sprite_template_path = '/assets/fish_sprite_{i}_30x30_red_fill.png'